[project]
name = "proyectoaa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.4",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.3",
    "psycopg[binary]>=3.3.4",
    "dotenv>=0.9.9",
    "plotly>=6.9.0",
    "openpyxl>=3.1.5",
    "contextily>=1.7.1",
]

[dependency-groups]
dev = [
    "folium>=0.20.0",
    "jupyter-collaboration>=5.0.0",
    "jupyterlab>=4.6.3",
    "jupyterlab-vim>=4.1.4",
    "mapclassify>=2.10.0",
    "odc-stac>=0.5.3",
    "pystac-client>=0.9.0",
    "stackstac>=0.5.0",
]
